# Generated by Django 6.0.2 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='flag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
