# Generated by Django 6.0.2 on 2026-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0517_taxonomychecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='gbif_consent',
            field=models.BooleanField(default=False, help_text='User consented to publishing these data to GBIF'),
        ),
    ]
