# Generated by Django 6.0.2 on 2026-05-04 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0518_add_gbif_consent_to_upload_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='col_enabled',
            field=models.BooleanField(default=False, help_text='Enable ColDP / ChecklistBank publishing for this module. Only modules with this flag set are listed in the public checklist API and included in external COL feeds.'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='checklist_version_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the ChecklistVersion in which this taxon first appeared in a published ColDP release.', null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='last_checklist_published_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the most recent published ChecklistVersion that included a change (addition or update) to this taxon.', null=True),
        ),
        migrations.CreateModel(
            name='ChecklistVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable UUID for this release. Embedded in generated PDFs and returned by the API.', primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Human-readable version string, e.g. "1.0", "2025.1".', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('doi', models.CharField(blank=True, default='', help_text='DOI assigned at publish time, e.g. https://doi.org/10.XXXX/YYYY.', max_length=255)),
                ('dataset_key', models.CharField(blank=True, default='', help_text='ChecklistBank / COL dataset key returned after upload.', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal release notes visible to editors.')),
                ('taxa_count', models.IntegerField(default=0)),
                ('additions_count', models.IntegerField(default=0)),
                ('updates_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(blank=True, db_column='checklist_id', help_text='Optional parent dataset record (ColDP dataset-level metadata).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='bims.taxonomychecklist')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_versions_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.licence')),
                ('previous_version', models.ForeignKey(blank=True, db_column='previous_version_id', help_text='Immediately preceding published version for this module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='bims.checklistversion')),
                ('published_by', models.ForeignKey(blank=True, db_column='published_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_versions_published', to=settings.AUTH_USER_MODEL)),
                ('taxon_group', models.ForeignKey(db_column='taxon_group_id', help_text='The module (TaxonGroup) this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_versions', to='bims.taxongroup')),
            ],
            options={
                'verbose_name': 'Checklist Version',
                'verbose_name_plural': 'Checklist Versions',
                'ordering': ['-created_at'],
                'unique_together': {('taxon_group', 'version')},
            },
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='captured_in_version',
            field=models.ForeignKey(blank=True, help_text='The first ChecklistVersion in which this approved proposal was included. Null = approved but not yet in any release.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_proposals', to='bims.checklistversion'),
        ),
        migrations.CreateModel(
            name='ChecklistSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(db_index=True, help_text='Stable taxon identifier used in checklist (str of Taxonomy.pk).', max_length=255)),
                ('parent_checklist_id', models.CharField(blank=True, default='', help_text='checklist_id of the parent taxon.', max_length=255)),
                ('basionym_checklist_id', models.CharField(blank=True, default='', help_text='checklist_id of the accepted taxon for synonyms.', max_length=255)),
                ('rank', models.CharField(blank=True, default='', max_length=50)),
                ('scientific_name', models.CharField(db_index=True, max_length=512)),
                ('authorship', models.CharField(blank=True, default='', max_length=255)),
                ('taxonomic_status', models.CharField(blank=True, default='', help_text='accepted, synonym, ambiguous synonym, misapplied, etc.', max_length=50)),
                ('name_status', models.CharField(blank=True, default='', help_text='establishmentMeans / name status from ColDP.', max_length=50)),
                ('kingdom', models.CharField(blank=True, default='', max_length=200)),
                ('phylum', models.CharField(blank=True, default='', max_length=200)),
                ('klass', models.CharField(blank=True, db_column='class', default='', max_length=200)),
                ('order', models.CharField(blank=True, default='', max_length=200)),
                ('family', models.CharField(blank=True, default='', max_length=200)),
                ('genus', models.CharField(blank=True, default='', max_length=200)),
                ('vernacular_names', models.JSONField(default=list, help_text='Snapshot of [{name, language}] at publish time.')),
                ('distributions', models.JSONField(default=list, help_text='Snapshot of [{area, status}] at publish time.')),
                ('reference_id', models.CharField(blank=True, default='', help_text='ColDP Reference.ID for the source reference.', max_length=255)),
                ('remarks', models.TextField(blank=True, default='', help_text='Free-text remarks field in ColDP NameUsage.')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('unchanged', 'Unchanged')], db_index=True, default='unchanged', help_text='Whether this taxon was added, updated, or unchanged in this version.', max_length=10)),
                ('checklist_version', models.ForeignKey(db_column='checklist_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_rows', to='bims.checklistversion')),
            ],
            options={
                'verbose_name': 'Checklist Snapshot Row',
                'verbose_name_plural': 'Checklist Snapshot Rows',
                'indexes': [models.Index(fields=['checklist_id', 'checklist_version'], name='bims_checkl_checkli_e8caec_idx')],
                'unique_together': {('checklist_version', 'checklist_id')},
            },
        ),
    ]
