# Generated by Django 6.0.2 on 2026-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0519_taxongroup_col_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistversion',
            name='deletions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistversion',
            name='is_publishing',
            field=models.BooleanField(default=False, help_text='True while the publish task is running. Cleared when publishing completes or fails.'),
        ),
        migrations.AlterField(
            model_name='checklistsnapshot',
            name='change_type',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('deleted', 'Deleted')], db_index=True, default='unchanged', help_text='Whether this taxon was added, updated, unchanged, or deleted in this version.', max_length=10),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='resource_type',
            field=models.CharField(choices=[('CSV', 'Csv'), ('XLS', 'Xls'), ('CHART', 'Chart'), ('TABLE', 'Table'), ('IMAGE', 'Image'), ('PDF', 'Pdf'), ('ZIP', 'Zip')], default='CSV', max_length=10),
        ),
    ]
