# Generated by Django 6.0.2 on 2026-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0522_sourcereference_publish_to_gbif'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='aphia_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='WoRMS AphiaID'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='aphia_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='WoRMS AphiaID'),
        ),
        migrations.AlterField(
            model_name='harvestsession',
            name='category',
            field=models.CharField(blank=True, choices=[('gbif', 'GBIF'), ('worms', 'WoRMS')], default='', max_length=50),
        ),
    ]
