# Generated by Django 6.0.4 on 2026-10-01 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0550_add_conservation_status_chart_use_taxon_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifPublishConfigProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Config',
                'verbose_name_plural': 'GBIF Configs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublishconfig',),
        ),
        migrations.CreateModel(
            name='GbifPublishProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Publish Schedule',
                'verbose_name_plural': 'GBIF Publish Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublish',),
        ),
        migrations.CreateModel(
            name='GbifPublishSessionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Publish Session',
                'verbose_name_plural': 'GBIF Publish Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublishsession',),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='gbif_metadata_file',
            field=models.FileField(blank=True, help_text='CSV with the dataset metadata published to GBIF. Columns: id, project_identifier, title, description, license, taxonomic_coverage, geographic_description, temporal_start, temporal_end, sampling_description, purpose. Without it the generic dataset description is published.', null=True, upload_to='source_reference_gbif_metadata/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
